/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdnrestconfcommunicator;

import javax.swing.JOptionPane;

/**
 *
 * @author pas
 */
public class SetFlowJFrame extends javax.swing.JFrame 
{

    private String node,username,password,controllerIp;
    HttpJsonRequest installFlowRequest;
    /**
     * Creates new form InstallFlowJFrame
     */
    public SetFlowJFrame(String node,String username, String password, String controllerIp) {
        initComponents();
        this.node = node;
        this.username = username;
        this.password = password;
        this.controllerIp = controllerIp;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        flowTextArea = new javax.swing.JTextArea();
        tableLbl = new javax.swing.JLabel();
        tableValueTextFld = new javax.swing.JTextField();
        flowIdlbl = new javax.swing.JLabel();
        flowIdValueTxtFld = new javax.swing.JTextField();
        hintLbl = new javax.swing.JLabel();
        installFlowBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        flowTextArea.setColumns(20);
        flowTextArea.setRows(5);
        jScrollPane1.setViewportView(flowTextArea);

        tableLbl.setText("Table");

        tableValueTextFld.setText("0");

        flowIdlbl.setText("Flow Id :");

        flowIdValueTxtFld.setText("1");

        hintLbl.setText("Insert flow parameters in json format");

        installFlowBtn.setText("Install Flow");
        installFlowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installFlowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tableLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tableValueTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(flowIdlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flowIdValueTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hintLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(installFlowBtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tableLbl)
                        .addComponent(tableValueTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flowIdlbl)
                        .addComponent(flowIdValueTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(hintLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(installFlowBtn)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void installFlowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installFlowBtnActionPerformed
        // TODO add your handling code here:
        installFlowRequest = new HttpJsonRequest();
        String baseUrl = PublicStatics.CONFIG_NODE_CONNECTOR_URL + node +
                "/table/" + tableValueTextFld.getText() +
                "/flow/" + flowIdValueTxtFld.getText();
        if (installFlowRequest.putRestconfInJson(username, password, controllerIp, baseUrl, flowTextArea.getText()))
            JOptionPane.showMessageDialog(null, "Flow Installed Successfully!!");
        else
            JOptionPane.showMessageDialog(null, "Error... Code " + installFlowRequest.callStatus);
             
            this.dispose();
        
    }//GEN-LAST:event_installFlowBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField flowIdValueTxtFld;
    private javax.swing.JLabel flowIdlbl;
    private javax.swing.JTextArea flowTextArea;
    private javax.swing.JLabel hintLbl;
    private javax.swing.JButton installFlowBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tableLbl;
    private javax.swing.JTextField tableValueTextFld;
    // End of variables declaration//GEN-END:variables
}
